apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaster-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kaster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: your-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: kaster-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: kaster-role
  apiGroup: rbac.authorization.k8s.io

